#!/usr/bin/env bash
# Copyright 2026 The Tipsy Authors
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Build a native tipsy-<version>-1-x86_64.pkg.tar.zst from the current source
# tree by reusing scripts/install-desktop.sh (DESTDIR staging).
#
# Usage:
#   packaging/arch/build-pacman.sh --version 1.2.3 --output-dir dist [--mode developer|official]
#
# --mode official (GitHub Actions only) marks the package
# release-repository-signed so a root-owned install from the GPG-signed
# pacman repository runs OfficialVerified; the default developer build stays
# development-unrestricted.
#
# makepkg is deliberately not used: the payload is the same /usr tree the
# .deb and .rpm use, assembled directly with bsdtar + zstd (fakeroot gives the
# root-owned entries pacman expects) plus .PKGINFO, .INSTALL, and .MTREE.
# Packages are signed in the repository step by Tipsy-repo
# update-pacman-repo.sh (--key-id), matching how .rpm signing works.
set -euo pipefail

fail() { printf 'build-pacman: %s\n' "$*" >&2; exit 1; }

version=
output_dir=
mode=developer
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) [[ $# -ge 2 ]] || fail 'missing --version value'; version=$2; shift 2 ;;
    --output-dir) [[ $# -ge 2 ]] || fail 'missing --output-dir value'; output_dir=$2; shift 2 ;;
    --mode) [[ $# -ge 2 ]] || fail 'missing --mode value'; mode=$2; shift 2 ;;
    -h|--help) sed -n '2,17p' "$0"; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

# pacman pkgver must not contain a hyphen; pkgrel is the fixed -1 below.
[[ "$version" =~ ^[0-9A-Za-z][0-9A-Za-z._+~]*$ && "$version" != *-* ]] || \
  fail 'invalid version (pacman pkgver must not contain a hyphen; use the upstream tag without v)'
[[ -n "$output_dir" ]] || fail '--output-dir is required'
[[ "$mode" == developer || "$mode" == official ]] || fail 'mode must be developer or official'
release_kind=development-unrestricted
[[ "$mode" != official ]] || release_kind=release-repository-signed
for tool in go bsdtar zstd fakeroot; do
  command -v "$tool" >/dev/null 2>&1 || fail "$tool is missing"
done

repo=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
packager=${PACKAGER:-"Tipsy Contributors <32bitx64bit@users.noreply.github.com>"}
[[ "$packager" != *$'\n'* && "$packager" != *$'\r'* ]] || fail 'invalid PACKAGER (must be a single line)'
mkdir -p "$output_dir"
output_dir=$(CDPATH= cd -- "$output_dir" && pwd)
pkg_name="tipsy-${version}-1-x86_64.pkg.tar.zst"
[[ ! -e "$output_dir/$pkg_name" ]] || fail "output already exists: $output_dir/$pkg_name"

work=$(mktemp -d "${TMPDIR:-/tmp}/tipsy-pacman.XXXXXXXX")
cleanup() {
  if [[ -n "${work:-}" && -d "$work" && "$work" == "${TMPDIR:-/tmp}"/tipsy-pacman.* ]]; then
    find "$work" -depth -delete
  fi
}
trap cleanup EXIT HUP INT TERM

stage="$work/stage"
mkdir -p "$stage"

# Reuse the canonical install layout: binaries, desktop files, icons,
# metainfo, licenses under PREFIX with DESTDIR staging.
DESTDIR="$stage" PREFIX=/usr VERSION="$version" CHANNEL=stable RELEASE_KIND="$release_kind" MEDIUM=pacman "$repo/scripts/install-desktop.sh"

builddate=${SOURCE_DATE_EPOCH:-$(date -u +%s)}
[[ "$builddate" =~ ^[0-9]+$ ]] || fail 'invalid builddate'

# Pacman runs post_install/post_upgrade from .INSTALL like dpkg/rpm run the
# deb postinst / rpm %post.
cat > "$stage/.INSTALL" <<'EOF'
post_install() {
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q /usr/share/applications || true
  fi
}
post_upgrade() {
  post_install
}
EOF
chmod 0644 "$stage/.INSTALL"

installed_size=$(du -sb "$stage" | cut -f1)
[[ "$installed_size" =~ ^[0-9]+$ ]] || fail 'could not compute installed size'

# Arch package names, mirroring the runtime dependency set of the .deb/.rpm.
cat > "$stage/.PKGINFO" <<EOF
# Generated by build-pacman.sh
pkgname = tipsy
pkgbase = tipsy
xdata = pkgtype=pkg
pkgver = ${version}-1
pkgdesc = Run the official Roblox Android client on Linux
url = https://github.com/32bitx64bit/Tipsy
builddate = $builddate
packager = $packager
size = $installed_size
arch = x86_64
license = GPL-3.0-or-later
depend = qt6-base
depend = libx11
depend = libxext
depend = libxrandr
depend = libxtst
depend = libxi
depend = libxcb
depend = mesa
depend = pango
depend = cairo
depend = libpulse
provides = tipsy
EOF
chmod 0644 "$stage/.PKGINFO"

pkg_file="$work/$pkg_name"
assemble="$work/assemble.sh"
cat > "$assemble" <<'EOF'
set -euo pipefail
pkgdir=$1
pkg_file=$2
mtree_list=$3
tar_list=$4
builddate=$5
# fakeroot makes every stat look root-owned; match makepkg's uniform mtimes.
find "$pkgdir" -exec touch -h -d "@$builddate" {} +
cd "$pkgdir"
find . -mindepth 1 ! -name .MTREE -printf '%P\0' | LC_ALL=C sort -z > "$mtree_list"
LANG=C bsdtar -cnf - --format=mtree \
  --options='!all,use-set,type,uid,gid,mode,time,size,sha256,link' \
  --null --files-from "$mtree_list" --exclude .MTREE | gzip -c -f -n > .MTREE
find . -mindepth 1 -printf '%P\0' | LC_ALL=C sort -z > "$tar_list"
bsdtar -cnf - --null --files-from "$tar_list" | zstd -c -T0 -19 > "$pkg_file"
EOF
fakeroot bash "$assemble" "$stage" "$pkg_file" "$work/mtree.list" "$work/tar.list" "$builddate"

# Sanity: package opens, ships both binaries and the release identity, and the
# .PKGINFO carries the expected version/arch/dependencies.
contents=$(bsdtar -tf "$pkg_file") || fail 'built package cannot be listed'
grep -qx '\.PKGINFO' <<<"$contents" || fail 'package is missing .PKGINFO'
grep -qx '\.INSTALL' <<<"$contents" || fail 'package is missing .INSTALL'
grep -qx '\.MTREE' <<<"$contents" || fail 'package is missing .MTREE'
grep -qx 'usr/bin/tipsy' <<<"$contents" || fail 'package is missing usr/bin/tipsy'
grep -qx 'usr/bin/tipsy-gui' <<<"$contents" || fail 'package is missing usr/bin/tipsy-gui'
grep -qx 'usr/share/tipsy/build-info.json' <<<"$contents" || fail 'package is missing build-info.json (release identity)'
pkginfo=$(bsdtar -xOf "$pkg_file" .PKGINFO) || fail 'package .PKGINFO cannot be read'
grep -qx "pkgver = ${version}-1" <<<"$pkginfo" || fail '.PKGINFO has the wrong pkgver'
grep -qx 'arch = x86_64' <<<"$pkginfo" || fail '.PKGINFO has the wrong arch'
grep -q '^depend = ' <<<"$pkginfo" || fail '.PKGINFO has no dependencies'
build_info=$(bsdtar -xOf "$pkg_file" usr/share/tipsy/build-info.json) || fail 'package build-info cannot be read'
grep -q '"format":"tipsy.build-info.v1"' <<<"$build_info" || fail 'build-info.json is not tipsy.build-info.v1'
grep -q "\"releaseKind\":\"${release_kind}\"" <<<"$build_info" || fail "build-info.json releaseKind is not ${release_kind}"
if command -v pacman >/dev/null 2>&1; then
  pacman -Qip "$pkg_file" >/dev/null || fail 'pacman rejects the built package metadata'
fi

mv -- "$pkg_file" "$output_dir/$pkg_name"
printf 'PACMAN: %s\n' "$output_dir/$pkg_name"
