/* Copyright 2026 The Tipsy Authors
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * JNIEnv / JavaVM vtables. C trampolines call //export Go (see internal/jni).
 */
#include "jni_bridge.h"

#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#ifndef TIPSY_JNI_STUTTER_DIAG_RECORD
#define TIPSY_JNI_STUTTER_DIAG_RECORD(family) ((void)(family))
#endif

/* Generated by cgo from //export in internal/jni. */
extern jint GoJNI_GetVersion(JNIEnv *env);
extern jclass GoJNI_FindClass(JNIEnv *env, char *name);
extern jclass GoJNI_DefineClass(JNIEnv *env, char *name, jobject loader, const jbyte *buf, jsize len);
extern jclass GoJNI_GetSuperclass(JNIEnv *env, jclass sub);
extern jboolean GoJNI_IsAssignableFrom(JNIEnv *env, jclass sub, jclass sup);
extern jint GoJNI_Throw(JNIEnv *env, jthrowable obj);
extern jint GoJNI_ThrowNew(JNIEnv *env, jclass clazz, char *msg);
extern jthrowable GoJNI_ExceptionOccurred(JNIEnv *env);
extern void GoJNI_ExceptionDescribe(JNIEnv *env);
extern void GoJNI_ExceptionClear(JNIEnv *env);
extern void GoJNI_FatalError(JNIEnv *env, char *msg);
extern jint GoJNI_PushLocalFrame(JNIEnv *env, jint capacity);
extern jobject GoJNI_PopLocalFrame(JNIEnv *env, jobject result);
extern jobject GoJNI_NewGlobalRef(JNIEnv *env, jobject lobj);
extern void GoJNI_DeleteGlobalRef(JNIEnv *env, jobject gref);
extern void GoJNI_DeleteLocalRef(JNIEnv *env, jobject obj);
extern jboolean GoJNI_IsSameObject(JNIEnv *env, jobject obj1, jobject obj2);
extern jobject GoJNI_NewLocalRef(JNIEnv *env, jobject ref);
extern jint GoJNI_EnsureLocalCapacity(JNIEnv *env, jint capacity);
extern jobject GoJNI_AllocObject(JNIEnv *env, jclass clazz);
extern jobject GoJNI_NewObjectA(JNIEnv *env, jclass clazz, jmethodID methodID, const jvalue *args);
extern jclass GoJNI_GetObjectClass(JNIEnv *env, jobject obj);
extern jboolean GoJNI_IsInstanceOf(JNIEnv *env, jobject obj, jclass clazz);
extern jmethodID GoJNI_GetMethodID(JNIEnv *env, jclass clazz, char *name, char *sig, jint is_static);
extern void GoJNI_CallA(JNIEnv *env, jobject obj, jclass clazz, jmethodID methodID, const jvalue *args, jint is_static, jint ret_kind, jvalue *out);
extern jfieldID GoJNI_GetFieldID(JNIEnv *env, jclass clazz, char *name, char *sig, jint is_static);
extern void GoJNI_GetField(JNIEnv *env, jobject obj, jclass clazz, jfieldID fieldID, jint is_static, jint ret_kind, jvalue *out);
extern void GoJNI_SetField(JNIEnv *env, jobject obj, jclass clazz, jfieldID fieldID, jvalue val, jint is_static, jint ret_kind);
extern jstring GoJNI_NewString(JNIEnv *env, const jchar *unicode, jsize len);
extern jsize GoJNI_GetStringLength(JNIEnv *env, jstring str);
extern const jchar *GoJNI_GetStringChars(JNIEnv *env, jstring str, jboolean *isCopy);
extern void GoJNI_ReleaseStringChars(JNIEnv *env, jstring str, const jchar *chars);
extern jstring GoJNI_NewStringUTF(JNIEnv *env, char *utf);
extern jsize GoJNI_GetStringUTFLength(JNIEnv *env, jstring str);
extern const char *GoJNI_GetStringUTFChars(JNIEnv *env, jstring str, jboolean *isCopy);
extern void GoJNI_ReleaseStringUTFChars(JNIEnv *env, jstring str, char *chars);
extern void GoJNI_GetStringRegion(JNIEnv *env, jstring str, jsize start, jsize len, jchar *buf);
extern void GoJNI_GetStringUTFRegion(JNIEnv *env, jstring str, jsize start, jsize len, char *buf);
extern jsize GoJNI_GetArrayLength(JNIEnv *env, jarray array);
extern jobjectArray GoJNI_NewObjectArray(JNIEnv *env, jsize len, jclass clazz, jobject init);
extern jobject GoJNI_GetObjectArrayElement(JNIEnv *env, jobjectArray array, jsize index);
extern void GoJNI_SetObjectArrayElement(JNIEnv *env, jobjectArray array, jsize index, jobject val);
extern jarray GoJNI_NewArray(JNIEnv *env, jint type_kind, jsize len);
extern void *GoJNI_GetArrayElements(JNIEnv *env, jarray array, jboolean *isCopy, jint type_kind);
extern void GoJNI_ReleaseArrayElements(JNIEnv *env, jarray array, void *elems, jint mode, jint type_kind);
extern void GoJNI_GetArrayRegion(JNIEnv *env, jarray array, jsize start, jsize len, void *buf, jint type_kind);
extern void GoJNI_SetArrayRegion(JNIEnv *env, jarray array, jsize start, jsize len, const void *buf, jint type_kind);
extern jint GoJNI_RegisterNatives(JNIEnv *env, jclass clazz, const JNINativeMethod *methods, jint nMethods);
extern jint GoJNI_UnregisterNatives(JNIEnv *env, jclass clazz);
extern jint GoJNI_MonitorEnter(JNIEnv *env, jobject obj);
extern jint GoJNI_MonitorExit(JNIEnv *env, jobject obj);
extern jint GoJNI_GetJavaVM(JNIEnv *env, JavaVM **vm);
extern jboolean GoJNI_ExceptionCheck(JNIEnv *env);
extern jobject GoJNI_NewDirectByteBuffer(JNIEnv *env, void *address, jlong capacity);
extern void *GoJNI_GetDirectBufferAddress(JNIEnv *env, jobject buf);
extern jlong GoJNI_GetDirectBufferCapacity(JNIEnv *env, jobject buf);
extern jobjectRefType GoJNI_GetObjectRefType(JNIEnv *env, jobject obj);
extern jobject GoJNI_NewWeakGlobalRef(JNIEnv *env, jobject obj);
extern void GoJNI_DeleteWeakGlobalRef(JNIEnv *env, jweak ref);
extern void GoJNI_EnvDetached(JNIEnv *env);
extern void GoJNI_Unimplemented(char *name);

static JavaVM g_vm;
static struct JNINativeInterface_ g_native;
static struct JNIInvokeInterface_ g_invoke;
static pthread_once_t g_init_once = PTHREAD_ONCE_INIT;
static pthread_key_t g_env_key;
static int g_init_result;
static JNIEnv *g_native_main_env;
static pthread_mutex_t g_env_count_mu = PTHREAD_MUTEX_INITIALIZER;
static size_t g_env_count;
static struct JNINativeInterface_ g_test_wrapped_native;
static pthread_mutex_t g_test_wrap_mu = PTHREAD_MUTEX_INITIALIZER;
static size_t g_test_wrapped_find_calls;
static int g_test_wrapped_owner_ok = 1;

struct tipsy_thread_env {
	JNIEnv env;
	int daemon;
};

_Static_assert(sizeof(JNIEnv) == sizeof(void *), "JNIEnv ABI");
_Static_assert(sizeof(JavaVM) == sizeof(void *), "JavaVM ABI");
_Static_assert(offsetof(struct JNINativeInterface_, GetVersion) == 4 * sizeof(void *), "JNI GetVersion slot");
_Static_assert(offsetof(struct JNINativeInterface_, GetObjectRefType) == 232 * sizeof(void *), "JNI GetObjectRefType slot");
_Static_assert(offsetof(struct JNIInvokeInterface_, AttachCurrentThread) == 4 * sizeof(void *), "VM Attach slot");
_Static_assert(offsetof(struct JNIInvokeInterface_, AttachCurrentThreadAsDaemon) == 7 * sizeof(void *), "VM daemon Attach slot");

/* Provided by internal/loader when the complete runtime is linked. JNI-only
 * tests intentionally exercise the current-pthread fallback. */
extern uintptr_t tipsy_call0_ret(void *fn) __attribute__((weak));
extern int64_t tipsy_call_p8(void *fn, void *a0, void *a1, void *a2, void *a3,
	void *a4, void *a5, void *a6, void *a7) __attribute__((weak));

int tipsy_pack_jargs(const char *sig, va_list ap, jvalue *out, int max)
{
	const char *p;
	int n = 0;

	if (sig == NULL || out == NULL || max <= 0) {
		return 0;
	}
	p = sig;
	if (*p == '(') {
		p++;
	}
	while (*p && *p != ')' && n < max) {
		switch (*p) {
		case 'Z':
		case 'B':
		case 'C':
		case 'S':
		case 'I':
			out[n++].i = va_arg(ap, int);
			p++;
			break;
		case 'J':
			out[n++].j = va_arg(ap, int64_t);
			p++;
			break;
		case 'F':
			out[n++].f = (float)va_arg(ap, double);
			p++;
			break;
		case 'D':
			out[n++].d = va_arg(ap, double);
			p++;
			break;
		case 'L':
			out[n++].l = va_arg(ap, jobject);
			while (*p && *p != ';') {
				p++;
			}
			if (*p == ';') {
				p++;
			}
			break;
		case '[':
			out[n++].l = va_arg(ap, jobject);
			p++;
			while (*p == '[') {
				p++;
			}
			if (*p == 'L') {
				while (*p && *p != ';') {
					p++;
				}
				if (*p == ';') {
					p++;
				}
			} else if (*p) {
				p++;
			}
			break;
		default:
			p++;
			break;
		}
	}
	return n;
}

static const char *method_sig(jmethodID mid)
{
	TipsyMethod *m = (TipsyMethod *)mid;
	if (m != NULL && m->magic == TIPSY_METHOD_MAGIC && m->sig != NULL) {
		return m->sig;
	}
	return "()V";
}

static jint JNICALL t_GetVersion(JNIEnv *env)
{
	return GoJNI_GetVersion(env);
}

static jclass JNICALL t_DefineClass(JNIEnv *env, const char *name, jobject loader, const jbyte *buf, jsize len)
{
	return GoJNI_DefineClass(env, (char *)name, loader, buf, len);
}

static jclass JNICALL t_FindClass(JNIEnv *env, const char *name)
{
	return GoJNI_FindClass(env, (char *)name);
}

static jmethodID JNICALL t_FromReflectedMethod(JNIEnv *env, jobject method)
{
	(void)env;
	(void)method;
	GoJNI_Unimplemented("FromReflectedMethod");
	return NULL;
}

static jfieldID JNICALL t_FromReflectedField(JNIEnv *env, jobject field)
{
	(void)env;
	(void)field;
	GoJNI_Unimplemented("FromReflectedField");
	return NULL;
}

static jobject JNICALL t_ToReflectedMethod(JNIEnv *env, jclass cls, jmethodID methodID, jboolean isStatic)
{
	(void)env;
	(void)cls;
	(void)methodID;
	(void)isStatic;
	GoJNI_Unimplemented("ToReflectedMethod");
	return NULL;
}

static jclass JNICALL t_GetSuperclass(JNIEnv *env, jclass sub)
{
	return GoJNI_GetSuperclass(env, sub);
}

static jboolean JNICALL t_IsAssignableFrom(JNIEnv *env, jclass sub, jclass sup)
{
	return GoJNI_IsAssignableFrom(env, sub, sup);
}

static jobject JNICALL t_ToReflectedField(JNIEnv *env, jclass cls, jfieldID fieldID, jboolean isStatic)
{
	(void)env;
	(void)cls;
	(void)fieldID;
	(void)isStatic;
	GoJNI_Unimplemented("ToReflectedField");
	return NULL;
}

static jint JNICALL t_Throw(JNIEnv *env, jthrowable obj)
{
	return GoJNI_Throw(env, obj);
}

static jint JNICALL t_ThrowNew(JNIEnv *env, jclass clazz, const char *msg)
{
	return GoJNI_ThrowNew(env, clazz, (char *)msg);
}

static jthrowable JNICALL t_ExceptionOccurred(JNIEnv *env)
{
	return GoJNI_ExceptionOccurred(env);
}

static void JNICALL t_ExceptionDescribe(JNIEnv *env)
{
	GoJNI_ExceptionDescribe(env);
}

static void JNICALL t_ExceptionClear(JNIEnv *env)
{
	GoJNI_ExceptionClear(env);
}

static void JNICALL t_FatalError(JNIEnv *env, const char *msg)
{
	GoJNI_FatalError(env, (char *)msg);
}

static jint JNICALL t_PushLocalFrame(JNIEnv *env, jint capacity)
{
	return GoJNI_PushLocalFrame(env, capacity);
}

static jobject JNICALL t_PopLocalFrame(JNIEnv *env, jobject result)
{
	return GoJNI_PopLocalFrame(env, result);
}

static jobject JNICALL t_NewGlobalRef(JNIEnv *env, jobject lobj)
{
	return GoJNI_NewGlobalRef(env, lobj);
}

static void JNICALL t_DeleteGlobalRef(JNIEnv *env, jobject gref)
{
	GoJNI_DeleteGlobalRef(env, gref);
}

static void JNICALL t_DeleteLocalRef(JNIEnv *env, jobject obj)
{
	GoJNI_DeleteLocalRef(env, obj);
}

static jboolean JNICALL t_IsSameObject(JNIEnv *env, jobject obj1, jobject obj2)
{
	return GoJNI_IsSameObject(env, obj1, obj2);
}

static jobject JNICALL t_NewLocalRef(JNIEnv *env, jobject ref)
{
	return GoJNI_NewLocalRef(env, ref);
}

static jint JNICALL t_EnsureLocalCapacity(JNIEnv *env, jint capacity)
{
	return GoJNI_EnsureLocalCapacity(env, capacity);
}

static jobject JNICALL t_AllocObject(JNIEnv *env, jclass clazz)
{
	return GoJNI_AllocObject(env, clazz);
}

static jobject JNICALL t_NewObjectA(JNIEnv *env, jclass clazz, jmethodID methodID, const jvalue *args)
{
	return GoJNI_NewObjectA(env, clazz, methodID, args);
}

static jobject JNICALL t_NewObjectV(JNIEnv *env, jclass clazz, jmethodID methodID, va_list args)
{
	jvalue packed[16];
	memset(packed, 0, sizeof packed);
	tipsy_pack_jargs(method_sig(methodID), args, packed, 16);
	return t_NewObjectA(env, clazz, methodID, packed);
}

static jobject JNICALL t_NewObject(JNIEnv *env, jclass clazz, jmethodID methodID, ...)
{
	va_list ap;
	jobject r;
	va_start(ap, methodID);
	r = t_NewObjectV(env, clazz, methodID, ap);
	va_end(ap);
	return r;
}

static jclass JNICALL t_GetObjectClass(JNIEnv *env, jobject obj)
{
	return GoJNI_GetObjectClass(env, obj);
}

static jboolean JNICALL t_IsInstanceOf(JNIEnv *env, jobject obj, jclass clazz)
{
	return GoJNI_IsInstanceOf(env, obj, clazz);
}

static jmethodID JNICALL t_GetMethodID(JNIEnv *env, jclass clazz, const char *name, const char *sig)
{
	return GoJNI_GetMethodID(env, clazz, (char *)name, (char *)sig, 0);
}

static jvalue call_a(JNIEnv *env, jobject obj, jclass clazz, jmethodID mid, const jvalue *args, jint is_static, jint kind)
{
	jvalue out;
	memset(&out, 0, sizeof out);
	TIPSY_JNI_STUTTER_DIAG_RECORD(is_static ? 1 : (clazz != NULL ? 2 : 0));
	GoJNI_CallA(env, obj, clazz, mid, args, is_static, kind, &out);
	return out;
}

static jvalue call_v(JNIEnv *env, jobject obj, jclass clazz, jmethodID mid, va_list ap, jint is_static, jint kind)
{
	jvalue packed[16];
	memset(packed, 0, sizeof packed);
	tipsy_pack_jargs(method_sig(mid), ap, packed, 16);
	return call_a(env, obj, clazz, mid, packed, is_static, kind);
}

#define CALL_VARARGS(ret, name, kind, field, is_static)                                                          \
	static ret JNICALL t_##name(JNIEnv *env, jobject obj, jmethodID methodID, ...)                           \
	{                                                                                                        \
		va_list ap;                                                                                      \
		jvalue v;                                                                                        \
		va_start(ap, methodID);                                                                          \
		v = call_v(env, obj, NULL, methodID, ap, is_static, kind);                                       \
		va_end(ap);                                                                                      \
		return v.field;                                                                                  \
	}

#define CALL_V(ret, name, kind, field, is_static)                                                                \
	static ret JNICALL t_##name(JNIEnv *env, jobject obj, jmethodID methodID, va_list args)                  \
	{                                                                                                        \
		jvalue v = call_v(env, obj, NULL, methodID, args, is_static, kind);                              \
		return v.field;                                                                                  \
	}

#define CALL_A(ret, name, kind, field, is_static)                                                                \
	static ret JNICALL t_##name(JNIEnv *env, jobject obj, jmethodID methodID, const jvalue *args)             \
	{                                                                                                        \
		jvalue v = call_a(env, obj, NULL, methodID, args, is_static, kind);                              \
		return v.field;                                                                                  \
	}

CALL_VARARGS(jobject, CallObjectMethod, 'L', l, 0)
CALL_V(jobject, CallObjectMethodV, 'L', l, 0)
CALL_A(jobject, CallObjectMethodA, 'L', l, 0)

CALL_VARARGS(jboolean, CallBooleanMethod, 'Z', z, 0)
CALL_V(jboolean, CallBooleanMethodV, 'Z', z, 0)
CALL_A(jboolean, CallBooleanMethodA, 'Z', z, 0)

CALL_VARARGS(jbyte, CallByteMethod, 'B', b, 0)
CALL_V(jbyte, CallByteMethodV, 'B', b, 0)
CALL_A(jbyte, CallByteMethodA, 'B', b, 0)

CALL_VARARGS(jchar, CallCharMethod, 'C', c, 0)
CALL_V(jchar, CallCharMethodV, 'C', c, 0)
CALL_A(jchar, CallCharMethodA, 'C', c, 0)

CALL_VARARGS(jshort, CallShortMethod, 'S', s, 0)
CALL_V(jshort, CallShortMethodV, 'S', s, 0)
CALL_A(jshort, CallShortMethodA, 'S', s, 0)

CALL_VARARGS(jint, CallIntMethod, 'I', i, 0)
CALL_V(jint, CallIntMethodV, 'I', i, 0)
CALL_A(jint, CallIntMethodA, 'I', i, 0)

CALL_VARARGS(jlong, CallLongMethod, 'J', j, 0)
CALL_V(jlong, CallLongMethodV, 'J', j, 0)
CALL_A(jlong, CallLongMethodA, 'J', j, 0)

CALL_VARARGS(jfloat, CallFloatMethod, 'F', f, 0)
CALL_V(jfloat, CallFloatMethodV, 'F', f, 0)
CALL_A(jfloat, CallFloatMethodA, 'F', f, 0)

CALL_VARARGS(jdouble, CallDoubleMethod, 'D', d, 0)
CALL_V(jdouble, CallDoubleMethodV, 'D', d, 0)
CALL_A(jdouble, CallDoubleMethodA, 'D', d, 0)

static void JNICALL t_CallVoidMethod(JNIEnv *env, jobject obj, jmethodID methodID, ...)
{
	va_list ap;
	va_start(ap, methodID);
	call_v(env, obj, NULL, methodID, ap, 0, 'V');
	va_end(ap);
}

static void JNICALL t_CallVoidMethodV(JNIEnv *env, jobject obj, jmethodID methodID, va_list args)
{
	call_v(env, obj, NULL, methodID, args, 0, 'V');
}

static void JNICALL t_CallVoidMethodA(JNIEnv *env, jobject obj, jmethodID methodID, const jvalue *args)
{
	call_a(env, obj, NULL, methodID, args, 0, 'V');
}

#define NVCALL_VARARGS(ret, name, kind, field)                                                                   \
	static ret JNICALL t_##name(JNIEnv *env, jobject obj, jclass clazz, jmethodID methodID, ...)             \
	{                                                                                                        \
		va_list ap;                                                                                      \
		jvalue v;                                                                                        \
		va_start(ap, methodID);                                                                          \
		v = call_v(env, obj, clazz, methodID, ap, 0, kind);                                              \
		va_end(ap);                                                                                      \
		return v.field;                                                                                  \
	}

#define NVCALL_V(ret, name, kind, field)                                                                         \
	static ret JNICALL t_##name(JNIEnv *env, jobject obj, jclass clazz, jmethodID methodID, va_list args)    \
	{                                                                                                        \
		jvalue v = call_v(env, obj, clazz, methodID, args, 0, kind);                                     \
		return v.field;                                                                                  \
	}

#define NVCALL_A(ret, name, kind, field)                                                                         \
	static ret JNICALL t_##name(JNIEnv *env, jobject obj, jclass clazz, jmethodID methodID, const jvalue *args) \
	{                                                                                                        \
		jvalue v = call_a(env, obj, clazz, methodID, args, 0, kind);                                     \
		return v.field;                                                                                  \
	}

NVCALL_VARARGS(jobject, CallNonvirtualObjectMethod, 'L', l)
NVCALL_V(jobject, CallNonvirtualObjectMethodV, 'L', l)
NVCALL_A(jobject, CallNonvirtualObjectMethodA, 'L', l)

NVCALL_VARARGS(jboolean, CallNonvirtualBooleanMethod, 'Z', z)
NVCALL_V(jboolean, CallNonvirtualBooleanMethodV, 'Z', z)
NVCALL_A(jboolean, CallNonvirtualBooleanMethodA, 'Z', z)

NVCALL_VARARGS(jbyte, CallNonvirtualByteMethod, 'B', b)
NVCALL_V(jbyte, CallNonvirtualByteMethodV, 'B', b)
NVCALL_A(jbyte, CallNonvirtualByteMethodA, 'B', b)

NVCALL_VARARGS(jchar, CallNonvirtualCharMethod, 'C', c)
NVCALL_V(jchar, CallNonvirtualCharMethodV, 'C', c)
NVCALL_A(jchar, CallNonvirtualCharMethodA, 'C', c)

NVCALL_VARARGS(jshort, CallNonvirtualShortMethod, 'S', s)
NVCALL_V(jshort, CallNonvirtualShortMethodV, 'S', s)
NVCALL_A(jshort, CallNonvirtualShortMethodA, 'S', s)

NVCALL_VARARGS(jint, CallNonvirtualIntMethod, 'I', i)
NVCALL_V(jint, CallNonvirtualIntMethodV, 'I', i)
NVCALL_A(jint, CallNonvirtualIntMethodA, 'I', i)

NVCALL_VARARGS(jlong, CallNonvirtualLongMethod, 'J', j)
NVCALL_V(jlong, CallNonvirtualLongMethodV, 'J', j)
NVCALL_A(jlong, CallNonvirtualLongMethodA, 'J', j)

NVCALL_VARARGS(jfloat, CallNonvirtualFloatMethod, 'F', f)
NVCALL_V(jfloat, CallNonvirtualFloatMethodV, 'F', f)
NVCALL_A(jfloat, CallNonvirtualFloatMethodA, 'F', f)

NVCALL_VARARGS(jdouble, CallNonvirtualDoubleMethod, 'D', d)
NVCALL_V(jdouble, CallNonvirtualDoubleMethodV, 'D', d)
NVCALL_A(jdouble, CallNonvirtualDoubleMethodA, 'D', d)

static void JNICALL t_CallNonvirtualVoidMethod(JNIEnv *env, jobject obj, jclass clazz, jmethodID methodID, ...)
{
	va_list ap;
	va_start(ap, methodID);
	call_v(env, obj, clazz, methodID, ap, 0, 'V');
	va_end(ap);
}

static void JNICALL t_CallNonvirtualVoidMethodV(JNIEnv *env, jobject obj, jclass clazz, jmethodID methodID, va_list args)
{
	call_v(env, obj, clazz, methodID, args, 0, 'V');
}

static void JNICALL t_CallNonvirtualVoidMethodA(JNIEnv *env, jobject obj, jclass clazz, jmethodID methodID, const jvalue *args)
{
	call_a(env, obj, clazz, methodID, args, 0, 'V');
}

static jfieldID JNICALL t_GetFieldID(JNIEnv *env, jclass clazz, const char *name, const char *sig)
{
	return GoJNI_GetFieldID(env, clazz, (char *)name, (char *)sig, 0);
}

static jobject JNICALL t_GetObjectField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'L', &v);
	return v.l;
}
static jboolean JNICALL t_GetBooleanField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'Z', &v);
	return v.z;
}
static jbyte JNICALL t_GetByteField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'B', &v);
	return v.b;
}
static jchar JNICALL t_GetCharField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'C', &v);
	return v.c;
}
static jshort JNICALL t_GetShortField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'S', &v);
	return v.s;
}
static jint JNICALL t_GetIntField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'I', &v);
	return v.i;
}
static jlong JNICALL t_GetLongField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'J', &v);
	return v.j;
}
static jfloat JNICALL t_GetFloatField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'F', &v);
	return v.f;
}
static jdouble JNICALL t_GetDoubleField(JNIEnv *env, jobject obj, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, obj, NULL, fieldID, 0, 'D', &v);
	return v.d;
}

static void JNICALL t_SetObjectField(JNIEnv *env, jobject obj, jfieldID fieldID, jobject val)
{
	jvalue v;
	v.l = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'L');
}
static void JNICALL t_SetBooleanField(JNIEnv *env, jobject obj, jfieldID fieldID, jboolean val)
{
	jvalue v;
	v.z = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'Z');
}
static void JNICALL t_SetByteField(JNIEnv *env, jobject obj, jfieldID fieldID, jbyte val)
{
	jvalue v;
	v.b = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'B');
}
static void JNICALL t_SetCharField(JNIEnv *env, jobject obj, jfieldID fieldID, jchar val)
{
	jvalue v;
	v.c = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'C');
}
static void JNICALL t_SetShortField(JNIEnv *env, jobject obj, jfieldID fieldID, jshort val)
{
	jvalue v;
	v.s = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'S');
}
static void JNICALL t_SetIntField(JNIEnv *env, jobject obj, jfieldID fieldID, jint val)
{
	jvalue v;
	v.i = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'I');
}
static void JNICALL t_SetLongField(JNIEnv *env, jobject obj, jfieldID fieldID, jlong val)
{
	jvalue v;
	v.j = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'J');
}
static void JNICALL t_SetFloatField(JNIEnv *env, jobject obj, jfieldID fieldID, jfloat val)
{
	jvalue v;
	v.f = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'F');
}
static void JNICALL t_SetDoubleField(JNIEnv *env, jobject obj, jfieldID fieldID, jdouble val)
{
	jvalue v;
	v.d = val;
	GoJNI_SetField(env, obj, NULL, fieldID, v, 0, 'D');
}

static jmethodID JNICALL t_GetStaticMethodID(JNIEnv *env, jclass clazz, const char *name, const char *sig)
{
	return GoJNI_GetMethodID(env, clazz, (char *)name, (char *)sig, 1);
}

#define SCALL_VARARGS(ret, name, kind, field)                                                                    \
	static ret JNICALL t_##name(JNIEnv *env, jclass clazz, jmethodID methodID, ...)                          \
	{                                                                                                        \
		va_list ap;                                                                                      \
		jvalue v;                                                                                        \
		va_start(ap, methodID);                                                                          \
		v = call_v(env, NULL, clazz, methodID, ap, 1, kind);                                             \
		va_end(ap);                                                                                      \
		return v.field;                                                                                  \
	}

#define SCALL_V(ret, name, kind, field)                                                                          \
	static ret JNICALL t_##name(JNIEnv *env, jclass clazz, jmethodID methodID, va_list args)                 \
	{                                                                                                        \
		jvalue v = call_v(env, NULL, clazz, methodID, args, 1, kind);                                    \
		return v.field;                                                                                  \
	}

#define SCALL_A(ret, name, kind, field)                                                                          \
	static ret JNICALL t_##name(JNIEnv *env, jclass clazz, jmethodID methodID, const jvalue *args)            \
	{                                                                                                        \
		jvalue v = call_a(env, NULL, clazz, methodID, args, 1, kind);                                    \
		return v.field;                                                                                  \
	}

SCALL_VARARGS(jobject, CallStaticObjectMethod, 'L', l)
SCALL_V(jobject, CallStaticObjectMethodV, 'L', l)
SCALL_A(jobject, CallStaticObjectMethodA, 'L', l)

SCALL_VARARGS(jboolean, CallStaticBooleanMethod, 'Z', z)
SCALL_V(jboolean, CallStaticBooleanMethodV, 'Z', z)
SCALL_A(jboolean, CallStaticBooleanMethodA, 'Z', z)

SCALL_VARARGS(jbyte, CallStaticByteMethod, 'B', b)
SCALL_V(jbyte, CallStaticByteMethodV, 'B', b)
SCALL_A(jbyte, CallStaticByteMethodA, 'B', b)

SCALL_VARARGS(jchar, CallStaticCharMethod, 'C', c)
SCALL_V(jchar, CallStaticCharMethodV, 'C', c)
SCALL_A(jchar, CallStaticCharMethodA, 'C', c)

SCALL_VARARGS(jshort, CallStaticShortMethod, 'S', s)
SCALL_V(jshort, CallStaticShortMethodV, 'S', s)
SCALL_A(jshort, CallStaticShortMethodA, 'S', s)

SCALL_VARARGS(jint, CallStaticIntMethod, 'I', i)
SCALL_V(jint, CallStaticIntMethodV, 'I', i)
SCALL_A(jint, CallStaticIntMethodA, 'I', i)

SCALL_VARARGS(jlong, CallStaticLongMethod, 'J', j)
SCALL_V(jlong, CallStaticLongMethodV, 'J', j)
SCALL_A(jlong, CallStaticLongMethodA, 'J', j)

SCALL_VARARGS(jfloat, CallStaticFloatMethod, 'F', f)
SCALL_V(jfloat, CallStaticFloatMethodV, 'F', f)
SCALL_A(jfloat, CallStaticFloatMethodA, 'F', f)

SCALL_VARARGS(jdouble, CallStaticDoubleMethod, 'D', d)
SCALL_V(jdouble, CallStaticDoubleMethodV, 'D', d)
SCALL_A(jdouble, CallStaticDoubleMethodA, 'D', d)

static void JNICALL t_CallStaticVoidMethod(JNIEnv *env, jclass clazz, jmethodID methodID, ...)
{
	va_list ap;
	va_start(ap, methodID);
	call_v(env, NULL, clazz, methodID, ap, 1, 'V');
	va_end(ap);
}

static void JNICALL t_CallStaticVoidMethodV(JNIEnv *env, jclass clazz, jmethodID methodID, va_list args)
{
	call_v(env, NULL, clazz, methodID, args, 1, 'V');
}

static void JNICALL t_CallStaticVoidMethodA(JNIEnv *env, jclass clazz, jmethodID methodID, const jvalue *args)
{
	call_a(env, NULL, clazz, methodID, args, 1, 'V');
}

static jfieldID JNICALL t_GetStaticFieldID(JNIEnv *env, jclass clazz, const char *name, const char *sig)
{
	return GoJNI_GetFieldID(env, clazz, (char *)name, (char *)sig, 1);
}

static jobject JNICALL t_GetStaticObjectField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'L', &v);
	return v.l;
}
static jboolean JNICALL t_GetStaticBooleanField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'Z', &v);
	return v.z;
}
static jbyte JNICALL t_GetStaticByteField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'B', &v);
	return v.b;
}
static jchar JNICALL t_GetStaticCharField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'C', &v);
	return v.c;
}
static jshort JNICALL t_GetStaticShortField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'S', &v);
	return v.s;
}
static jint JNICALL t_GetStaticIntField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'I', &v);
	return v.i;
}
static jlong JNICALL t_GetStaticLongField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'J', &v);
	return v.j;
}
static jfloat JNICALL t_GetStaticFloatField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'F', &v);
	return v.f;
}
static jdouble JNICALL t_GetStaticDoubleField(JNIEnv *env, jclass clazz, jfieldID fieldID)
{
	jvalue v;
	memset(&v, 0, sizeof v);
	GoJNI_GetField(env, NULL, clazz, fieldID, 1, 'D', &v);
	return v.d;
}

static void JNICALL t_SetStaticObjectField(JNIEnv *env, jclass clazz, jfieldID fieldID, jobject val)
{
	jvalue v;
	v.l = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'L');
}
static void JNICALL t_SetStaticBooleanField(JNIEnv *env, jclass clazz, jfieldID fieldID, jboolean val)
{
	jvalue v;
	v.z = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'Z');
}
static void JNICALL t_SetStaticByteField(JNIEnv *env, jclass clazz, jfieldID fieldID, jbyte val)
{
	jvalue v;
	v.b = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'B');
}
static void JNICALL t_SetStaticCharField(JNIEnv *env, jclass clazz, jfieldID fieldID, jchar val)
{
	jvalue v;
	v.c = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'C');
}
static void JNICALL t_SetStaticShortField(JNIEnv *env, jclass clazz, jfieldID fieldID, jshort val)
{
	jvalue v;
	v.s = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'S');
}
static void JNICALL t_SetStaticIntField(JNIEnv *env, jclass clazz, jfieldID fieldID, jint val)
{
	jvalue v;
	v.i = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'I');
}
static void JNICALL t_SetStaticLongField(JNIEnv *env, jclass clazz, jfieldID fieldID, jlong val)
{
	jvalue v;
	v.j = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'J');
}
static void JNICALL t_SetStaticFloatField(JNIEnv *env, jclass clazz, jfieldID fieldID, jfloat val)
{
	jvalue v;
	v.f = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'F');
}
static void JNICALL t_SetStaticDoubleField(JNIEnv *env, jclass clazz, jfieldID fieldID, jdouble val)
{
	jvalue v;
	v.d = val;
	GoJNI_SetField(env, NULL, clazz, fieldID, v, 1, 'D');
}

static jstring JNICALL t_NewString(JNIEnv *env, const jchar *unicode, jsize len)
{
	return GoJNI_NewString(env, unicode, len);
}
static jsize JNICALL t_GetStringLength(JNIEnv *env, jstring str)
{
	return GoJNI_GetStringLength(env, str);
}
static const jchar *JNICALL t_GetStringChars(JNIEnv *env, jstring str, jboolean *isCopy)
{
	return GoJNI_GetStringChars(env, str, isCopy);
}
static void JNICALL t_ReleaseStringChars(JNIEnv *env, jstring str, const jchar *chars)
{
	GoJNI_ReleaseStringChars(env, str, chars);
}
static jstring JNICALL t_NewStringUTF(JNIEnv *env, const char *utf)
{
	return GoJNI_NewStringUTF(env, (char *)utf);
}
static jsize JNICALL t_GetStringUTFLength(JNIEnv *env, jstring str)
{
	return GoJNI_GetStringUTFLength(env, str);
}
static const char *JNICALL t_GetStringUTFChars(JNIEnv *env, jstring str, jboolean *isCopy)
{
	return GoJNI_GetStringUTFChars(env, str, isCopy);
}
static void JNICALL t_ReleaseStringUTFChars(JNIEnv *env, jstring str, const char *chars)
{
	GoJNI_ReleaseStringUTFChars(env, str, (char *)chars);
}

static jsize JNICALL t_GetArrayLength(JNIEnv *env, jarray array)
{
	return GoJNI_GetArrayLength(env, array);
}
static jobjectArray JNICALL t_NewObjectArray(JNIEnv *env, jsize len, jclass clazz, jobject init)
{
	return GoJNI_NewObjectArray(env, len, clazz, init);
}
static jobject JNICALL t_GetObjectArrayElement(JNIEnv *env, jobjectArray array, jsize index)
{
	return GoJNI_GetObjectArrayElement(env, array, index);
}
static void JNICALL t_SetObjectArrayElement(JNIEnv *env, jobjectArray array, jsize index, jobject val)
{
	GoJNI_SetObjectArrayElement(env, array, index, val);
}

#define NEWARR(name, kind)                                                                                       \
	static jarray JNICALL t_##name(JNIEnv *env, jsize len)                                                   \
	{                                                                                                        \
		return GoJNI_NewArray(env, kind, len);                                                           \
	}

NEWARR(NewBooleanArray, 'Z')
NEWARR(NewByteArray, 'B')
NEWARR(NewCharArray, 'C')
NEWARR(NewShortArray, 'S')
NEWARR(NewIntArray, 'I')
NEWARR(NewLongArray, 'J')
NEWARR(NewFloatArray, 'F')
NEWARR(NewDoubleArray, 'D')

#define GETELEMS(ret, name, kind)                                                                                \
	static ret *JNICALL t_##name(JNIEnv *env, jarray array, jboolean *isCopy)                                \
	{                                                                                                        \
		return (ret *)GoJNI_GetArrayElements(env, array, isCopy, kind);                                  \
	}

GETELEMS(jboolean, GetBooleanArrayElements, 'Z')
GETELEMS(jbyte, GetByteArrayElements, 'B')
GETELEMS(jchar, GetCharArrayElements, 'C')
GETELEMS(jshort, GetShortArrayElements, 'S')
GETELEMS(jint, GetIntArrayElements, 'I')
GETELEMS(jlong, GetLongArrayElements, 'J')
GETELEMS(jfloat, GetFloatArrayElements, 'F')
GETELEMS(jdouble, GetDoubleArrayElements, 'D')

#define RELELEMS(elem, name, kind)                                                                               \
	static void JNICALL t_##name(JNIEnv *env, jarray array, elem *elems, jint mode)                          \
	{                                                                                                        \
		GoJNI_ReleaseArrayElements(env, array, elems, mode, kind);                                       \
	}

RELELEMS(jboolean, ReleaseBooleanArrayElements, 'Z')
RELELEMS(jbyte, ReleaseByteArrayElements, 'B')
RELELEMS(jchar, ReleaseCharArrayElements, 'C')
RELELEMS(jshort, ReleaseShortArrayElements, 'S')
RELELEMS(jint, ReleaseIntArrayElements, 'I')
RELELEMS(jlong, ReleaseLongArrayElements, 'J')
RELELEMS(jfloat, ReleaseFloatArrayElements, 'F')
RELELEMS(jdouble, ReleaseDoubleArrayElements, 'D')

#define GETREG(elem, name, kind)                                                                                 \
	static void JNICALL t_##name(JNIEnv *env, jarray array, jsize start, jsize len, elem *buf)               \
	{                                                                                                        \
		GoJNI_GetArrayRegion(env, array, start, len, buf, kind);                                         \
	}

GETREG(jboolean, GetBooleanArrayRegion, 'Z')
GETREG(jbyte, GetByteArrayRegion, 'B')
GETREG(jchar, GetCharArrayRegion, 'C')
GETREG(jshort, GetShortArrayRegion, 'S')
GETREG(jint, GetIntArrayRegion, 'I')
GETREG(jlong, GetLongArrayRegion, 'J')
GETREG(jfloat, GetFloatArrayRegion, 'F')
GETREG(jdouble, GetDoubleArrayRegion, 'D')

#define SETREG(elem, name, kind)                                                                                 \
	static void JNICALL t_##name(JNIEnv *env, jarray array, jsize start, jsize len, const elem *buf)         \
	{                                                                                                        \
		GoJNI_SetArrayRegion(env, array, start, len, buf, kind);                                         \
	}

SETREG(jboolean, SetBooleanArrayRegion, 'Z')
SETREG(jbyte, SetByteArrayRegion, 'B')
SETREG(jchar, SetCharArrayRegion, 'C')
SETREG(jshort, SetShortArrayRegion, 'S')
SETREG(jint, SetIntArrayRegion, 'I')
SETREG(jlong, SetLongArrayRegion, 'J')
SETREG(jfloat, SetFloatArrayRegion, 'F')
SETREG(jdouble, SetDoubleArrayRegion, 'D')

static jint JNICALL t_RegisterNatives(JNIEnv *env, jclass clazz, const JNINativeMethod *methods, jint nMethods)
{
	return GoJNI_RegisterNatives(env, clazz, methods, nMethods);
}
static jint JNICALL t_UnregisterNatives(JNIEnv *env, jclass clazz)
{
	return GoJNI_UnregisterNatives(env, clazz);
}
static jint JNICALL t_MonitorEnter(JNIEnv *env, jobject obj)
{
	return GoJNI_MonitorEnter(env, obj);
}
static jint JNICALL t_MonitorExit(JNIEnv *env, jobject obj)
{
	return GoJNI_MonitorExit(env, obj);
}
static jint JNICALL t_GetJavaVM(JNIEnv *env, JavaVM **vm)
{
	return GoJNI_GetJavaVM(env, vm);
}
static void JNICALL t_GetStringRegion(JNIEnv *env, jstring str, jsize start, jsize len, jchar *buf)
{
	GoJNI_GetStringRegion(env, str, start, len, buf);
}
static void JNICALL t_GetStringUTFRegion(JNIEnv *env, jstring str, jsize start, jsize len, char *buf)
{
	GoJNI_GetStringUTFRegion(env, str, start, len, buf);
}
static void *JNICALL t_GetPrimitiveArrayCritical(JNIEnv *env, jarray array, jboolean *isCopy)
{
	return GoJNI_GetArrayElements(env, array, isCopy, 'B');
}
static void JNICALL t_ReleasePrimitiveArrayCritical(JNIEnv *env, jarray array, void *carray, jint mode)
{
	GoJNI_ReleaseArrayElements(env, array, carray, mode, 'B');
}
static const jchar *JNICALL t_GetStringCritical(JNIEnv *env, jstring str, jboolean *isCopy)
{
	return GoJNI_GetStringChars(env, str, isCopy);
}
static void JNICALL t_ReleaseStringCritical(JNIEnv *env, jstring str, const jchar *carray)
{
	GoJNI_ReleaseStringChars(env, str, carray);
}
static jweak JNICALL t_NewWeakGlobalRef(JNIEnv *env, jobject obj)
{
	return GoJNI_NewWeakGlobalRef(env, obj);
}
static void JNICALL t_DeleteWeakGlobalRef(JNIEnv *env, jweak ref)
{
	GoJNI_DeleteWeakGlobalRef(env, ref);
}
static jboolean JNICALL t_ExceptionCheck(JNIEnv *env)
{
	return GoJNI_ExceptionCheck(env);
}
static jobject JNICALL t_NewDirectByteBuffer(JNIEnv *env, void *address, jlong capacity)
{
	return GoJNI_NewDirectByteBuffer(env, address, capacity);
}
static void *JNICALL t_GetDirectBufferAddress(JNIEnv *env, jobject buf)
{
	return GoJNI_GetDirectBufferAddress(env, buf);
}
static jlong JNICALL t_GetDirectBufferCapacity(JNIEnv *env, jobject buf)
{
	return GoJNI_GetDirectBufferCapacity(env, buf);
}
static jobjectRefType JNICALL t_GetObjectRefType(JNIEnv *env, jobject obj)
{
	return GoJNI_GetObjectRefType(env, obj);
}

static void thread_env_destroy(void *value)
{
	struct tipsy_thread_env *thread_env = value;

	if (thread_env == NULL) {
		return;
	}
	/* Publish detachment while the environment identity is still valid. */
	GoJNI_EnvDetached(&thread_env->env);
	pthread_mutex_lock(&g_env_count_mu);
	if (g_env_count != 0) {
		g_env_count--;
	}
	pthread_mutex_unlock(&g_env_count_mu);
	free(thread_env);
}

static int supported_jni_version(jint version)
{
	return version == JNI_VERSION_1_1 || version == JNI_VERSION_1_2 ||
		version == JNI_VERSION_1_4 || version == JNI_VERSION_1_6;
}

static jint JNICALL t_DestroyJavaVM(JavaVM *vm)
{
	/* Tipsy's native-main executor is intentionally process-lifetime and has no
	 * stop/join protocol yet. Returning success would falsely promise that all
	 * non-daemon threads and callbacks were quiesced. */
	(void)vm;
	return JNI_ERR;
}

static jint attach_current_thread(JavaVM *vm, JNIEnv **penv, void *args, int daemon)
{
	struct tipsy_thread_env *thread_env;

	(void)args;
	if (penv == NULL) {
		return JNI_ERR;
	}
	*penv = NULL;
	if (vm != &g_vm) {
		return JNI_ERR;
	}
	thread_env = pthread_getspecific(g_env_key);
	if (thread_env == NULL) {
		thread_env = calloc(1, sizeof(*thread_env));
		if (thread_env == NULL) {
			return JNI_ERR;
		}
		thread_env->env.functions = &g_native;
		thread_env->daemon = daemon != 0;
		if (pthread_setspecific(g_env_key, thread_env) != 0) {
			free(thread_env);
			return JNI_ERR;
		}
		pthread_mutex_lock(&g_env_count_mu);
		g_env_count++;
		pthread_mutex_unlock(&g_env_count_mu);
	}
	*penv = &thread_env->env;
	return JNI_OK;
}

static jint JNICALL t_AttachCurrentThread(JavaVM *vm, JNIEnv **penv, void *args)
{
	return attach_current_thread(vm, penv, args, 0);
}

static jint JNICALL t_DetachCurrentThread(JavaVM *vm)
{
	struct tipsy_thread_env *thread_env;

	if (vm != &g_vm) {
		return JNI_ERR;
	}
	thread_env = pthread_getspecific(g_env_key);
	if (thread_env == NULL) {
		return JNI_OK;
	}
	if (pthread_setspecific(g_env_key, NULL) != 0) {
		return JNI_ERR;
	}
	thread_env_destroy(thread_env);
	return JNI_OK;
}

static jint JNICALL t_GetEnv(JavaVM *vm, void **penv, jint version)
{
	struct tipsy_thread_env *thread_env;

	if (penv == NULL) {
		return JNI_ERR;
	}
	*penv = NULL;
	if (vm != &g_vm) {
		return JNI_ERR;
	}
	if (!supported_jni_version(version)) {
		return JNI_EVERSION;
	}
	thread_env = pthread_getspecific(g_env_key);
	if (thread_env == NULL) {
		return JNI_EDETACHED;
	}
	*penv = &thread_env->env;
	return JNI_OK;
}

static jint JNICALL t_AttachCurrentThreadAsDaemon(JavaVM *vm, JNIEnv **penv, void *args)
{
	return attach_current_thread(vm, penv, args, 1);
}

static void fill_native(struct JNINativeInterface_ *t)
{
	memset(t, 0, sizeof(*t));
	t->GetVersion = t_GetVersion;
	t->DefineClass = t_DefineClass;
	t->FindClass = t_FindClass;
	t->FromReflectedMethod = t_FromReflectedMethod;
	t->FromReflectedField = t_FromReflectedField;
	t->ToReflectedMethod = t_ToReflectedMethod;
	t->GetSuperclass = t_GetSuperclass;
	t->IsAssignableFrom = t_IsAssignableFrom;
	t->ToReflectedField = t_ToReflectedField;
	t->Throw = t_Throw;
	t->ThrowNew = t_ThrowNew;
	t->ExceptionOccurred = t_ExceptionOccurred;
	t->ExceptionDescribe = t_ExceptionDescribe;
	t->ExceptionClear = t_ExceptionClear;
	t->FatalError = t_FatalError;
	t->PushLocalFrame = t_PushLocalFrame;
	t->PopLocalFrame = t_PopLocalFrame;
	t->NewGlobalRef = t_NewGlobalRef;
	t->DeleteGlobalRef = t_DeleteGlobalRef;
	t->DeleteLocalRef = t_DeleteLocalRef;
	t->IsSameObject = t_IsSameObject;
	t->NewLocalRef = t_NewLocalRef;
	t->EnsureLocalCapacity = t_EnsureLocalCapacity;
	t->AllocObject = t_AllocObject;
	t->NewObject = t_NewObject;
	t->NewObjectV = t_NewObjectV;
	t->NewObjectA = t_NewObjectA;
	t->GetObjectClass = t_GetObjectClass;
	t->IsInstanceOf = t_IsInstanceOf;
	t->GetMethodID = t_GetMethodID;
	t->CallObjectMethod = t_CallObjectMethod;
	t->CallObjectMethodV = t_CallObjectMethodV;
	t->CallObjectMethodA = t_CallObjectMethodA;
	t->CallBooleanMethod = t_CallBooleanMethod;
	t->CallBooleanMethodV = t_CallBooleanMethodV;
	t->CallBooleanMethodA = t_CallBooleanMethodA;
	t->CallByteMethod = t_CallByteMethod;
	t->CallByteMethodV = t_CallByteMethodV;
	t->CallByteMethodA = t_CallByteMethodA;
	t->CallCharMethod = t_CallCharMethod;
	t->CallCharMethodV = t_CallCharMethodV;
	t->CallCharMethodA = t_CallCharMethodA;
	t->CallShortMethod = t_CallShortMethod;
	t->CallShortMethodV = t_CallShortMethodV;
	t->CallShortMethodA = t_CallShortMethodA;
	t->CallIntMethod = t_CallIntMethod;
	t->CallIntMethodV = t_CallIntMethodV;
	t->CallIntMethodA = t_CallIntMethodA;
	t->CallLongMethod = t_CallLongMethod;
	t->CallLongMethodV = t_CallLongMethodV;
	t->CallLongMethodA = t_CallLongMethodA;
	t->CallFloatMethod = t_CallFloatMethod;
	t->CallFloatMethodV = t_CallFloatMethodV;
	t->CallFloatMethodA = t_CallFloatMethodA;
	t->CallDoubleMethod = t_CallDoubleMethod;
	t->CallDoubleMethodV = t_CallDoubleMethodV;
	t->CallDoubleMethodA = t_CallDoubleMethodA;
	t->CallVoidMethod = t_CallVoidMethod;
	t->CallVoidMethodV = t_CallVoidMethodV;
	t->CallVoidMethodA = t_CallVoidMethodA;
	t->CallNonvirtualObjectMethod = t_CallNonvirtualObjectMethod;
	t->CallNonvirtualObjectMethodV = t_CallNonvirtualObjectMethodV;
	t->CallNonvirtualObjectMethodA = t_CallNonvirtualObjectMethodA;
	t->CallNonvirtualBooleanMethod = t_CallNonvirtualBooleanMethod;
	t->CallNonvirtualBooleanMethodV = t_CallNonvirtualBooleanMethodV;
	t->CallNonvirtualBooleanMethodA = t_CallNonvirtualBooleanMethodA;
	t->CallNonvirtualByteMethod = t_CallNonvirtualByteMethod;
	t->CallNonvirtualByteMethodV = t_CallNonvirtualByteMethodV;
	t->CallNonvirtualByteMethodA = t_CallNonvirtualByteMethodA;
	t->CallNonvirtualCharMethod = t_CallNonvirtualCharMethod;
	t->CallNonvirtualCharMethodV = t_CallNonvirtualCharMethodV;
	t->CallNonvirtualCharMethodA = t_CallNonvirtualCharMethodA;
	t->CallNonvirtualShortMethod = t_CallNonvirtualShortMethod;
	t->CallNonvirtualShortMethodV = t_CallNonvirtualShortMethodV;
	t->CallNonvirtualShortMethodA = t_CallNonvirtualShortMethodA;
	t->CallNonvirtualIntMethod = t_CallNonvirtualIntMethod;
	t->CallNonvirtualIntMethodV = t_CallNonvirtualIntMethodV;
	t->CallNonvirtualIntMethodA = t_CallNonvirtualIntMethodA;
	t->CallNonvirtualLongMethod = t_CallNonvirtualLongMethod;
	t->CallNonvirtualLongMethodV = t_CallNonvirtualLongMethodV;
	t->CallNonvirtualLongMethodA = t_CallNonvirtualLongMethodA;
	t->CallNonvirtualFloatMethod = t_CallNonvirtualFloatMethod;
	t->CallNonvirtualFloatMethodV = t_CallNonvirtualFloatMethodV;
	t->CallNonvirtualFloatMethodA = t_CallNonvirtualFloatMethodA;
	t->CallNonvirtualDoubleMethod = t_CallNonvirtualDoubleMethod;
	t->CallNonvirtualDoubleMethodV = t_CallNonvirtualDoubleMethodV;
	t->CallNonvirtualDoubleMethodA = t_CallNonvirtualDoubleMethodA;
	t->CallNonvirtualVoidMethod = t_CallNonvirtualVoidMethod;
	t->CallNonvirtualVoidMethodV = t_CallNonvirtualVoidMethodV;
	t->CallNonvirtualVoidMethodA = t_CallNonvirtualVoidMethodA;
	t->GetFieldID = t_GetFieldID;
	t->GetObjectField = t_GetObjectField;
	t->GetBooleanField = t_GetBooleanField;
	t->GetByteField = t_GetByteField;
	t->GetCharField = t_GetCharField;
	t->GetShortField = t_GetShortField;
	t->GetIntField = t_GetIntField;
	t->GetLongField = t_GetLongField;
	t->GetFloatField = t_GetFloatField;
	t->GetDoubleField = t_GetDoubleField;
	t->SetObjectField = t_SetObjectField;
	t->SetBooleanField = t_SetBooleanField;
	t->SetByteField = t_SetByteField;
	t->SetCharField = t_SetCharField;
	t->SetShortField = t_SetShortField;
	t->SetIntField = t_SetIntField;
	t->SetLongField = t_SetLongField;
	t->SetFloatField = t_SetFloatField;
	t->SetDoubleField = t_SetDoubleField;
	t->GetStaticMethodID = t_GetStaticMethodID;
	t->CallStaticObjectMethod = t_CallStaticObjectMethod;
	t->CallStaticObjectMethodV = t_CallStaticObjectMethodV;
	t->CallStaticObjectMethodA = t_CallStaticObjectMethodA;
	t->CallStaticBooleanMethod = t_CallStaticBooleanMethod;
	t->CallStaticBooleanMethodV = t_CallStaticBooleanMethodV;
	t->CallStaticBooleanMethodA = t_CallStaticBooleanMethodA;
	t->CallStaticByteMethod = t_CallStaticByteMethod;
	t->CallStaticByteMethodV = t_CallStaticByteMethodV;
	t->CallStaticByteMethodA = t_CallStaticByteMethodA;
	t->CallStaticCharMethod = t_CallStaticCharMethod;
	t->CallStaticCharMethodV = t_CallStaticCharMethodV;
	t->CallStaticCharMethodA = t_CallStaticCharMethodA;
	t->CallStaticShortMethod = t_CallStaticShortMethod;
	t->CallStaticShortMethodV = t_CallStaticShortMethodV;
	t->CallStaticShortMethodA = t_CallStaticShortMethodA;
	t->CallStaticIntMethod = t_CallStaticIntMethod;
	t->CallStaticIntMethodV = t_CallStaticIntMethodV;
	t->CallStaticIntMethodA = t_CallStaticIntMethodA;
	t->CallStaticLongMethod = t_CallStaticLongMethod;
	t->CallStaticLongMethodV = t_CallStaticLongMethodV;
	t->CallStaticLongMethodA = t_CallStaticLongMethodA;
	t->CallStaticFloatMethod = t_CallStaticFloatMethod;
	t->CallStaticFloatMethodV = t_CallStaticFloatMethodV;
	t->CallStaticFloatMethodA = t_CallStaticFloatMethodA;
	t->CallStaticDoubleMethod = t_CallStaticDoubleMethod;
	t->CallStaticDoubleMethodV = t_CallStaticDoubleMethodV;
	t->CallStaticDoubleMethodA = t_CallStaticDoubleMethodA;
	t->CallStaticVoidMethod = t_CallStaticVoidMethod;
	t->CallStaticVoidMethodV = t_CallStaticVoidMethodV;
	t->CallStaticVoidMethodA = t_CallStaticVoidMethodA;
	t->GetStaticFieldID = t_GetStaticFieldID;
	t->GetStaticObjectField = t_GetStaticObjectField;
	t->GetStaticBooleanField = t_GetStaticBooleanField;
	t->GetStaticByteField = t_GetStaticByteField;
	t->GetStaticCharField = t_GetStaticCharField;
	t->GetStaticShortField = t_GetStaticShortField;
	t->GetStaticIntField = t_GetStaticIntField;
	t->GetStaticLongField = t_GetStaticLongField;
	t->GetStaticFloatField = t_GetStaticFloatField;
	t->GetStaticDoubleField = t_GetStaticDoubleField;
	t->SetStaticObjectField = t_SetStaticObjectField;
	t->SetStaticBooleanField = t_SetStaticBooleanField;
	t->SetStaticByteField = t_SetStaticByteField;
	t->SetStaticCharField = t_SetStaticCharField;
	t->SetStaticShortField = t_SetStaticShortField;
	t->SetStaticIntField = t_SetStaticIntField;
	t->SetStaticLongField = t_SetStaticLongField;
	t->SetStaticFloatField = t_SetStaticFloatField;
	t->SetStaticDoubleField = t_SetStaticDoubleField;
	t->NewString = t_NewString;
	t->GetStringLength = t_GetStringLength;
	t->GetStringChars = t_GetStringChars;
	t->ReleaseStringChars = t_ReleaseStringChars;
	t->NewStringUTF = t_NewStringUTF;
	t->GetStringUTFLength = t_GetStringUTFLength;
	t->GetStringUTFChars = t_GetStringUTFChars;
	t->ReleaseStringUTFChars = t_ReleaseStringUTFChars;
	t->GetArrayLength = t_GetArrayLength;
	t->NewObjectArray = t_NewObjectArray;
	t->GetObjectArrayElement = t_GetObjectArrayElement;
	t->SetObjectArrayElement = t_SetObjectArrayElement;
	t->NewBooleanArray = t_NewBooleanArray;
	t->NewByteArray = t_NewByteArray;
	t->NewCharArray = t_NewCharArray;
	t->NewShortArray = t_NewShortArray;
	t->NewIntArray = t_NewIntArray;
	t->NewLongArray = t_NewLongArray;
	t->NewFloatArray = t_NewFloatArray;
	t->NewDoubleArray = t_NewDoubleArray;
	t->GetBooleanArrayElements = t_GetBooleanArrayElements;
	t->GetByteArrayElements = t_GetByteArrayElements;
	t->GetCharArrayElements = t_GetCharArrayElements;
	t->GetShortArrayElements = t_GetShortArrayElements;
	t->GetIntArrayElements = t_GetIntArrayElements;
	t->GetLongArrayElements = t_GetLongArrayElements;
	t->GetFloatArrayElements = t_GetFloatArrayElements;
	t->GetDoubleArrayElements = t_GetDoubleArrayElements;
	t->ReleaseBooleanArrayElements = t_ReleaseBooleanArrayElements;
	t->ReleaseByteArrayElements = t_ReleaseByteArrayElements;
	t->ReleaseCharArrayElements = t_ReleaseCharArrayElements;
	t->ReleaseShortArrayElements = t_ReleaseShortArrayElements;
	t->ReleaseIntArrayElements = t_ReleaseIntArrayElements;
	t->ReleaseLongArrayElements = t_ReleaseLongArrayElements;
	t->ReleaseFloatArrayElements = t_ReleaseFloatArrayElements;
	t->ReleaseDoubleArrayElements = t_ReleaseDoubleArrayElements;
	t->GetBooleanArrayRegion = t_GetBooleanArrayRegion;
	t->GetByteArrayRegion = t_GetByteArrayRegion;
	t->GetCharArrayRegion = t_GetCharArrayRegion;
	t->GetShortArrayRegion = t_GetShortArrayRegion;
	t->GetIntArrayRegion = t_GetIntArrayRegion;
	t->GetLongArrayRegion = t_GetLongArrayRegion;
	t->GetFloatArrayRegion = t_GetFloatArrayRegion;
	t->GetDoubleArrayRegion = t_GetDoubleArrayRegion;
	t->SetBooleanArrayRegion = t_SetBooleanArrayRegion;
	t->SetByteArrayRegion = t_SetByteArrayRegion;
	t->SetCharArrayRegion = t_SetCharArrayRegion;
	t->SetShortArrayRegion = t_SetShortArrayRegion;
	t->SetIntArrayRegion = t_SetIntArrayRegion;
	t->SetLongArrayRegion = t_SetLongArrayRegion;
	t->SetFloatArrayRegion = t_SetFloatArrayRegion;
	t->SetDoubleArrayRegion = t_SetDoubleArrayRegion;
	t->RegisterNatives = t_RegisterNatives;
	t->UnregisterNatives = t_UnregisterNatives;
	t->MonitorEnter = t_MonitorEnter;
	t->MonitorExit = t_MonitorExit;
	t->GetJavaVM = t_GetJavaVM;
	t->GetStringRegion = t_GetStringRegion;
	t->GetStringUTFRegion = t_GetStringUTFRegion;
	t->GetPrimitiveArrayCritical = t_GetPrimitiveArrayCritical;
	t->ReleasePrimitiveArrayCritical = t_ReleasePrimitiveArrayCritical;
	t->GetStringCritical = t_GetStringCritical;
	t->ReleaseStringCritical = t_ReleaseStringCritical;
	t->NewWeakGlobalRef = t_NewWeakGlobalRef;
	t->DeleteWeakGlobalRef = t_DeleteWeakGlobalRef;
	t->ExceptionCheck = t_ExceptionCheck;
	t->NewDirectByteBuffer = t_NewDirectByteBuffer;
	t->GetDirectBufferAddress = t_GetDirectBufferAddress;
	t->GetDirectBufferCapacity = t_GetDirectBufferCapacity;
	t->GetObjectRefType = t_GetObjectRefType;
}

static void init_bridge_once(void)
{
	fill_native(&g_native);
	memset(&g_invoke, 0, sizeof g_invoke);
	g_invoke.DestroyJavaVM = t_DestroyJavaVM;
	g_invoke.AttachCurrentThread = t_AttachCurrentThread;
	g_invoke.DetachCurrentThread = t_DetachCurrentThread;
	g_invoke.GetEnv = t_GetEnv;
	g_invoke.AttachCurrentThreadAsDaemon = t_AttachCurrentThreadAsDaemon;
	g_vm.functions = &g_invoke;
	g_init_result = pthread_key_create(&g_env_key, thread_env_destroy);
}

int tipsy_jni_init(void)
{
	if (pthread_once(&g_init_once, init_bridge_once) != 0 || g_init_result != 0) {
		return -1;
	}
	return 0;
}

JNIEnv *tipsy_jni_env(void)
{
	void *env = NULL;

	if (tipsy_jni_init() != 0) {
		return NULL;
	}
	if (t_GetEnv(&g_vm, &env, JNI_VERSION_1_6) != JNI_OK) {
		return NULL;
	}
	return env;
}

JNIEnv *tipsy_jni_current_env(void)
{
	struct tipsy_thread_env *thread_env;

	if (tipsy_jni_init() != 0) {
		return NULL;
	}
	thread_env = pthread_getspecific(g_env_key);
	return thread_env == NULL ? NULL : &thread_env->env;
}

jint tipsy_jni_attach_current_thread(JNIEnv **env, int daemon)
{
	if (tipsy_jni_init() != 0) {
		if (env != NULL) {
			*env = NULL;
		}
		return JNI_ERR;
	}
	if (daemon) {
		return t_AttachCurrentThreadAsDaemon(&g_vm, env, NULL);
	}
	return t_AttachCurrentThread(&g_vm, env, NULL);
}

jint tipsy_jni_detach_current_thread(void)
{
	if (tipsy_jni_init() != 0) {
		return JNI_ERR;
	}
	return t_DetachCurrentThread(&g_vm);
}

jint tipsy_jni_get_env(void **env, jint version)
{
	if (tipsy_jni_init() != 0) {
		if (env != NULL) {
			*env = NULL;
		}
		return JNI_ERR;
	}
	return t_GetEnv(&g_vm, env, version);
}

static uintptr_t attach_native_main_job(void)
{
	JNIEnv *env = NULL;

	if (t_AttachCurrentThread(&g_vm, &env, NULL) != JNI_OK) {
		return 0;
	}
	return (uintptr_t)env;
}

static uintptr_t current_env_job(void)
{
	void *env = NULL;

	if (t_GetEnv(&g_vm, &env, JNI_VERSION_1_6) != JNI_OK) {
		return 0;
	}
	return (uintptr_t)env;
}

JNIEnv *tipsy_jni_attach_native_main(void)
{
	JNIEnv *env;

	if (tipsy_jni_init() != 0) {
		return NULL;
	}
	if (tipsy_call0_ret != NULL) {
		env = (JNIEnv *)tipsy_call0_ret((void *)attach_native_main_job);
	} else {
		/* JNI-only binaries do not link the runtime's C Main executor. */
		env = (JNIEnv *)attach_native_main_job();
	}
	g_native_main_env = env;
	return env;
}

size_t tipsy_jni_attached_thread_count(void)
{
	size_t count;

	pthread_mutex_lock(&g_env_count_mu);
	count = g_env_count;
	pthread_mutex_unlock(&g_env_count_mu);
	return count;
}

static void *test_attach_and_exit_thread(void *unused)
{
	JNIEnv *env = NULL;

	(void)unused;
	return (void *)(intptr_t)t_AttachCurrentThread(&g_vm, &env, NULL);
}

int tipsy_jni_test_attach_and_exit(void)
{
	pthread_t thread;
	void *result = (void *)(intptr_t)JNI_ERR;

	if (tipsy_jni_init() != 0 ||
		pthread_create(&thread, NULL, test_attach_and_exit_thread, NULL) != 0) {
		return JNI_ERR;
	}
	if (pthread_join(thread, &result) != 0) {
		return JNI_ERR;
	}
	return (int)(intptr_t)result;
}

int tipsy_jni_test_native_main_env_is(JNIEnv *expected)
{
	if (expected == NULL || tipsy_call0_ret == NULL) {
		return 0;
	}
	return tipsy_call0_ret((void *)current_env_job) == (uintptr_t)expected;
}

static jclass JNICALL test_wrapped_FindClass(JNIEnv *env, const char *name)
{
	pthread_mutex_lock(&g_test_wrap_mu);
	g_test_wrapped_find_calls++;
	if (tipsy_jni_current_env() != env || env != g_native_main_env) {
		g_test_wrapped_owner_ok = 0;
	}
	pthread_mutex_unlock(&g_test_wrap_mu);
	return g_native.FindClass(env, name);
}

int tipsy_jni_test_wrap_native_main(int enabled)
{
	if (g_native_main_env == NULL) {
		return JNI_ERR;
	}
	pthread_mutex_lock(&g_test_wrap_mu);
	if (enabled) {
		g_test_wrapped_native = g_native;
		g_test_wrapped_native.FindClass = test_wrapped_FindClass;
		g_native_main_env->functions = &g_test_wrapped_native;
		g_test_wrapped_find_calls = 0;
		g_test_wrapped_owner_ok = 1;
	} else {
		g_native_main_env->functions = &g_native;
	}
	pthread_mutex_unlock(&g_test_wrap_mu);
	return JNI_OK;
}

size_t tipsy_jni_test_wrapped_find_calls(int *owner_ok)
{
	size_t calls;

	pthread_mutex_lock(&g_test_wrap_mu);
	calls = g_test_wrapped_find_calls;
	if (owner_ok != NULL) {
		*owner_ok = g_test_wrapped_owner_ok;
	}
	pthread_mutex_unlock(&g_test_wrap_mu);
	return calls;
}

void *tipsy_jni_native_interface(void)
{
	if (tipsy_jni_init() != 0) {
		return NULL;
	}
	return (void *)&g_native;
}

JavaVM *tipsy_jni_java_vm(void)
{
	if (tipsy_jni_init() != 0) {
		return NULL;
	}
	return &g_vm;
}

enum env_call_mode {
	ENV_CALL_INVALID = -1,
	ENV_CALL_DIRECT,
	ENV_CALL_NATIVE_MAIN,
};

static enum env_call_mode env_owner_call_mode(JNIEnv *env)
{
	if (tipsy_jni_current_env() == env) {
		return ENV_CALL_DIRECT;
	}
	if (env == g_native_main_env && tipsy_call_p8 != NULL) {
		return ENV_CALL_NATIVE_MAIN;
	}
	return ENV_CALL_INVALID;
}

static int64_t owner_FindClass(void *env, void *name, void *a2, void *a3,
	void *a4, void *a5, void *a6, void *a7)
{
	(void)a2; (void)a3; (void)a4; (void)a5; (void)a6; (void)a7;
	return (int64_t)(intptr_t)((JNIEnv *)env)->functions->FindClass(env, name);
}

jclass tipsy_jni_FindClass(JNIEnv *env, const char *name)
{
	enum env_call_mode mode;

	if (env == NULL || env->functions == NULL || env->functions->FindClass == NULL) {
		return NULL;
	}
	mode = env_owner_call_mode(env);
	if (mode == ENV_CALL_NATIVE_MAIN) {
		return (jclass)(intptr_t)tipsy_call_p8((void *)owner_FindClass, env,
			(void *)name, NULL, NULL, NULL, NULL, NULL, NULL);
	}
	if (mode == ENV_CALL_INVALID) {
		return NULL;
	}
	return env->functions->FindClass(env, name);
}

static int64_t owner_NewStringUTF(void *env, void *utf, void *a2, void *a3,
	void *a4, void *a5, void *a6, void *a7)
{
	(void)a2; (void)a3; (void)a4; (void)a5; (void)a6; (void)a7;
	return (int64_t)(intptr_t)((JNIEnv *)env)->functions->NewStringUTF(env, utf);
}

jstring tipsy_jni_NewStringUTF(JNIEnv *env, const char *utf)
{
	enum env_call_mode mode;

	if (env == NULL || env->functions == NULL || env->functions->NewStringUTF == NULL) {
		return NULL;
	}
	mode = env_owner_call_mode(env);
	if (mode == ENV_CALL_NATIVE_MAIN) {
		return (jstring)(intptr_t)tipsy_call_p8((void *)owner_NewStringUTF, env,
			(void *)utf, NULL, NULL, NULL, NULL, NULL, NULL);
	}
	if (mode == ENV_CALL_INVALID) {
		return NULL;
	}
	return env->functions->NewStringUTF(env, utf);
}

static int64_t owner_GetStringUTFChars(void *env, void *str, void *is_copy,
	void *a3, void *a4, void *a5, void *a6, void *a7)
{
	(void)a3; (void)a4; (void)a5; (void)a6; (void)a7;
	return (int64_t)(intptr_t)((JNIEnv *)env)->functions->GetStringUTFChars(env, str, is_copy);
}

const char *tipsy_jni_GetStringUTFChars(JNIEnv *env, jstring str, jboolean *isCopy)
{
	enum env_call_mode mode;

	if (env == NULL || env->functions == NULL || env->functions->GetStringUTFChars == NULL) {
		return NULL;
	}
	mode = env_owner_call_mode(env);
	if (mode == ENV_CALL_NATIVE_MAIN) {
		return (const char *)(intptr_t)tipsy_call_p8((void *)owner_GetStringUTFChars,
			env, str, isCopy, NULL, NULL, NULL, NULL, NULL);
	}
	if (mode == ENV_CALL_INVALID) {
		return NULL;
	}
	return env->functions->GetStringUTFChars(env, str, isCopy);
}

static int64_t owner_ReleaseStringUTFChars(void *env, void *str, void *chars,
	void *a3, void *a4, void *a5, void *a6, void *a7)
{
	(void)a3; (void)a4; (void)a5; (void)a6; (void)a7;
	((JNIEnv *)env)->functions->ReleaseStringUTFChars(env, str, chars);
	return 0;
}

void tipsy_jni_ReleaseStringUTFChars(JNIEnv *env, jstring str, const char *chars)
{
	enum env_call_mode mode;

	if (env == NULL || env->functions == NULL || env->functions->ReleaseStringUTFChars == NULL) {
		return;
	}
	mode = env_owner_call_mode(env);
	if (mode == ENV_CALL_NATIVE_MAIN) {
		(void)tipsy_call_p8((void *)owner_ReleaseStringUTFChars, env, str,
			(void *)chars, NULL, NULL, NULL, NULL, NULL);
		return;
	}
	if (mode == ENV_CALL_INVALID) {
		return;
	}
	env->functions->ReleaseStringUTFChars(env, str, chars);
}

static int64_t owner_AllocObject(void *env, void *clazz, void *a2, void *a3,
	void *a4, void *a5, void *a6, void *a7)
{
	(void)a2; (void)a3; (void)a4; (void)a5; (void)a6; (void)a7;
	return (int64_t)(intptr_t)((JNIEnv *)env)->functions->AllocObject(env, clazz);
}

jobject tipsy_jni_AllocObject(JNIEnv *env, jclass clazz)
{
	enum env_call_mode mode;

	if (env == NULL || env->functions == NULL || env->functions->AllocObject == NULL) {
		return NULL;
	}
	mode = env_owner_call_mode(env);
	if (mode == ENV_CALL_NATIVE_MAIN) {
		return (jobject)(intptr_t)tipsy_call_p8((void *)owner_AllocObject, env,
			clazz, NULL, NULL, NULL, NULL, NULL, NULL);
	}
	if (mode == ENV_CALL_INVALID) {
		return NULL;
	}
	return env->functions->AllocObject(env, clazz);
}

static int64_t owner_NewByteArray(void *env, void *len, void *a2, void *a3,
	void *a4, void *a5, void *a6, void *a7)
{
	(void)a2; (void)a3; (void)a4; (void)a5; (void)a6; (void)a7;
	return (int64_t)(intptr_t)((JNIEnv *)env)->functions->NewByteArray(env, (jsize)(intptr_t)len);
}

jbyteArray tipsy_jni_NewByteArray(JNIEnv *env, jsize len)
{
	enum env_call_mode mode;

	if (env == NULL || env->functions == NULL || env->functions->NewByteArray == NULL) {
		return NULL;
	}
	mode = env_owner_call_mode(env);
	if (mode == ENV_CALL_NATIVE_MAIN) {
		return (jbyteArray)(intptr_t)tipsy_call_p8((void *)owner_NewByteArray, env,
			(void *)(intptr_t)len, NULL, NULL, NULL, NULL, NULL, NULL);
	}
	if (mode == ENV_CALL_INVALID) {
		return NULL;
	}
	return env->functions->NewByteArray(env, len);
}

void tipsy_jvalue_zero(jvalue *v)
{
	if (v != NULL) {
		memset(v, 0, sizeof(*v));
	}
}

void tipsy_jvalue_set_l(jvalue *v, jobject l)
{
	if (v != NULL) {
		v->l = l;
	}
}

void tipsy_jvalue_set_i(jvalue *v, jint i)
{
	if (v != NULL) {
		v->i = i;
	}
}

void tipsy_jvalue_set_j(jvalue *v, jlong x)
{
	if (v != NULL) {
		v->j = x;
	}
}

void tipsy_jvalue_set_z(jvalue *v, jboolean z)
{
	if (v != NULL) {
		v->z = z;
	}
}

void tipsy_jvalue_set_d(jvalue *v, jdouble d)
{
	if (v != NULL) {
		v->d = d;
	}
}

void tipsy_jvalue_set_f(jvalue *v, jfloat f)
{
	if (v != NULL) {
		v->f = f;
	}
}

jobject tipsy_jvalue_l(const jvalue *v)
{
	return v != NULL ? v->l : NULL;
}

jint tipsy_jvalue_i(const jvalue *v)
{
	return v != NULL ? v->i : 0;
}

jlong tipsy_jvalue_j(const jvalue *v)
{
	return v != NULL ? v->j : 0;
}

jobject tipsy_jvalue_l_at(const jvalue *args, int i)
{
	if (args == NULL || i < 0) {
		return NULL;
	}
	return args[i].l;
}
